server:
  port: 7001

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eurekaserver7002:7002/eureka/
  instance:
    prefer-ip-address: true
    hostname: eurekaserver7001
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}